# Generated by Django 4.2.4 on 2023-08-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ma_Works",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proj_name", models.CharField(max_length=100)),
                ("proj_img", models.ImageField(upload_to="images/")),
                ("proj_link", models.CharField(max_length=200)),
                ("proj_desp", models.TextField()),
            ],
        ),
    ]
